### ISSUE TITLE
failed download of scheduel

### ISSUE THREAD

**Issue by partymike** [binhex/arch-get-iplayer#2]
firstly thanks for this docker, and all the other excellent works :-)

when running as get a long list of warnings:

WARNING: Failed to download programme schedule http://www.bbc.co.uk/cbbc/programmes/schedules/this_week.xml

11:41:12
2017-04-28 12:41:12,816 DEBG 'get-iplayer' stdout output:

11:41:12
WARNING: Failed to download programme schedule http://www.bbc.co.uk/cbeebies/programmes/schedules/last_week.xml

11:41:13
2017-04-28 12:41:13,155 DEBG 'get-iplayer' stdout output:

11:41:13
WARNING: Failed to download programme schedule http://www.bbc.co.uk/cbeebies/programmes/schedules/this_week.xml
stdout

11:41:13
WARNING: Failed to download programme schedule http://www.bbc.co.uk/s4c/programmes/schedules/last_week.xml
stdout

any idea why? Am guessing if this fails it will never match a show...

Running docker on synology with DSM 6.1

**Comment by binhex** [comment]
please try latest image
