### ISSUE TITLE
Failed to download schedule

### ISSUE THREAD

**Issue by mlemen** [binhex/arch-get-iplayer#3]
get_iplayer has been updated to 3.06 to fix the issue.

(would it be easier to pick up the latest ARCH?    Or would that be too unstable?)

Thanks,
Mike

**Comment by binhex** [comment]
3.06 is in the latest docker image, does this fix this?

**Comment by mlemen** [comment]
3.05 is in my docker image, from my logs:

2017-11-15 22:00:43,145 DEBG 'get-iplayer' stdout output:
get_iplayer v3.05, Copyright (C) 2008-2010 Phil Lewis

Could it be that the published project does not contain your latest commit (changing arch-base:2017102500)

Thanks
